### ISSUE TITLE
bug: does not show all extensions in main dropdown

### ISSUE THREAD

**Issue by joeblew99** [sergiokas/Extensity#12]
if i toggle them in the chrome extensions thing i can see them.

If i press the extensity logo to see them, some are not visible.

Could it be that one of the loaded extensions is messing with extensity. Have kind of seen that before.

**Comment by sergiokas** [comment]
@joeblew99 v1.3.0 solved this issue.

**Comment by joeblew99** [comment]
@sergiokas thansk for update :)
