### ISSUE TITLE
Bug: Some times the view does not have the correct position

### ISSUE THREAD

**Issue by robertodias180** [sergiokas/Extensity#13]
This is what i see, and does not allow me to scroll up.
this is on MacOS (not sure if happen on windows)
<img width="295" alt="screen shot 2017-01-25 at 15 42 23" src="https://cloud.githubusercontent.com/assets/6941489/22297407/0e2ab112-e315-11e6-88d9-469c3a82d965.png">

**Comment by sergiokas** [comment]
@robertodias180 v1.3.0 solved this issue.
