### ISSUE TITLE
Save current enabled/ disabled extensions to a Group/ State? 

### ISSUE THREAD

**Issue by xbliss** [sergiokas/Extensity#2]
Save current enabled/ disabled extensions to a Group/ State?

How are you? Wanted your help with this. 

Is there a way to "Save" Current set of enabled & disabled Extensions as a "Primary" or "main" Group? 

There are many times I enable disable extensions without Extensiry, I'd like to be able to take "existing" current state of extensions and save them as a Group. 

For now, my intent is to "save" this "CURRENT" 'state' and then disable all extensions for a Chrome User Profile migration and then do a "restore" of the saved "CURRENT" state to have it back the same way. 

What steps do I need to take for this? 

Thanks & regards, 
- A

**Comment by luyuu** [comment]
ooooo

**Comment by xbliss** [comment]
??

**Comment by sergiokas** [comment]
Already implemented
