### ISSUE TITLE
sync between two devices

### ISSUE THREAD

**Issue by holdjohnh** [sergiokas/Extensity#22]
I have two devices
I want to use different extensities

![screenshot 2018-01-18 at 00 06 23](https://user-images.githubusercontent.com/16971410/35052856-8c29db78-fbe3-11e7-894e-9fdcb0a8de98.png)

if i use chromebook
    then i use 'chromebook' profiles
else if i use pc
    then i use 'pc' profiles

thanks

**Comment by sergiokas** [comment]
This has been released in v1.4.0 with the new Chrome Cloud Sync support. Thanks!
