### ISSUE TITLE
[Bug] Hide in Chrome menu

### ISSUE THREAD

**Issue by ElectronicManuel** [sergiokas/Extensity#24]
I love Extensity and use the profiles feature all the time. 
However there are some extensions I want enabled but hidden in the chrome menu (ad-blocker). As soon as I switch to a profile where an extension hidden in the chrome menu gets disabled and I switch back to a profile where it is, a seemingly random amount of extensions gets hidden in the chrome menu.
This is super annoying because it effectively prevents me from hiding any extensions while still using them.

**Comment by gpion** [comment]
Same problem with the _"switch enabled extension"_ button: when toggling, on my profile, all visible extension (minus one) gets hidden.
The visible/invisible state of each extension should be saved.

**Comment by connah0047** [comment]
I am having this same problem and would like to inquire if there is any plan to address it any time soon.

Extension: Extensity 1.10.0
Browser: Version 75.0.3770.90 (Official Build) (64-bit)
OS: Windows 7 Professional, SP1 (64-bit)

STEPS TO REPRODUCE
-------------------------
1) Open Chrome Browser.
2) Ensure that in addition to Extensity, several other extensions are installed, enabled, and their icons being displayed on the Chrome toolbar.
3) Right-click on any other extension icon besides Extensity and select "Hide in Chrome menu". Observe the selected icon disappear as expected.
4) Click on the Extensity extension icon and flip the switch labeled "Switch enabled extensions off" to turn off all extensions. Observe all extension icons except Extensity disappear as expected.
5) Click on the Extensity extension icon and flip the switch labeled "Switch enabled extensions off" to turn on all extensions. Observe all extension icons except Extensity remain hidden.

**Comment by amitg87** [comment]
#46 is duplicate.
**Not possible as of right now**
There is no way we could override chrome behaviour of hiding extension in toolbar.
I don't see this getting addressed anytime soon.
There are no APIs available to manage the toolbar.

**Comment by sergiokas** [comment]
See https://twitter.com/ExtensityChrome/status/1301165128742834183

Closing for now, will reopen if Chrome ever gets support for pinning/unpinning.

**Comment by adrianhalid** [comment]
> See https://twitter.com/ExtensityChrome/status/1301165128742834183
> 
> Closing for now, will reopen if Chrome ever gets support for pinning/unpinning.

Here is a possible work around for users.
Create a profile called "All".
Include all extensions in this profile.
Select the "All" profile and pin everything.
Now when you switch between any other profile they stay pinned.
