### ISSUE TITLE
Differentiate between types of extensions

### ISSUE THREAD

**Issue by amitg87** [sergiokas/Extensity#25]
As as chrome extension developer - I might have two versions of same chrome extension installed.
There should be visual cue on differentiating between unpacked and packed extension.

[Chrome Management API](https://developer.chrome.com/extensions/management#type-ExtensionType)

Such difference is also showcased on Chrome Extension Page - chrome://extensions/

**Comment by sergiokas** [comment]
This is a good idea. I'll work on it.

**Comment by sergiokas** [comment]
Released in 1.7.0
