### ISSUE TITLE
Small Request

### ISSUE THREAD

**Issue by mikhoul** [sergiokas/Extensity#30]
Hi and thanks for this useful extension,

What I'd like to have is a small button beside the name of the extension to open the option page of the extension.

![image](https://user-images.githubusercontent.com/5678673/41010209-112427d8-6904-11e8-859d-aad015b3bdb7.png)

Maybe a small "Gear" icon would be more suited than my ugly orange button/circle 😜

Maybe something like this: http://icons.iconarchive.com/icons/elegantthemes/beautiful-flat-one-color/128/gear-icon.png

![image](https://user-images.githubusercontent.com/5678673/41010342-cbe092a0-6904-11e8-8bc6-a818a6d82798.png)

Best Regards :octocat:

**Comment by amitg87** [comment]
Already supported - 

1. user icon - will take you to profiles
2. gear icon - will take you to options.

**Comment by mikhoul** [comment]
[**@amitg87**](https://github.com/amitg87) commented on [6 juin 2018 à 06:28 UTC−4](https://github.com/sergiokas/Extensity/issues/30#issuecomment-395021592 "2018-06-06T10:28:01Z - Replied by Github Reply Comments"):
> Already supported -
> 
> 1.  user icon - will take you to profiles
> 2.  gear icon - will take you to options.

@sergiokas 

No, I was talking about the options of the extensions like in _SimpleExtManager_: 

![image](https://user-images.githubusercontent.com/5678673/41074054-30b791ae-69d4-11e8-9ec1-c118dcd36072.png)



Regards :octocat:

**Comment by sergiokas** [comment]
@amitg87 @mikhoul this is being rolled out in 1.6.0 since this morning. Check for your Extensity update. Thanks!

**Comment by mikhoul** [comment]
Thanks a lot 👍👍👍
