### ISSUE TITLE
Module settings backup / restore functionality

### ISSUE THREAD

**Issue by eMPee584** [sergiokas/Extensity#37]
Ok just a dream: a Titanium-Backup-like extensions manager that can save and restore extensions & their settings.

**Comment by sergiokas** [comment]
@eMPee584 that's not a bad idea, but Chrome is dropping support for extensions that would try to install other extensions. This somewhat supported in entrerprise-managed Chrome instances: https://support.google.com/chrome/a/answer/1289314?hl=en

**Comment by eMPee584** [comment]
Gee, how the chrome project is run and which technical choices are made is so not what I associate with an open source ethic..
