### ISSUE TITLE
Big bug when you have a lot of extension: Profiles are not saved 

### ISSUE THREAD

**Issue by mikhoul** [sergiokas/Extensity#43]
I was trying to debug a conflict this morning between extension so I wanted to save my "profile" before disabling some extensions and find the problem.

So when I was saving my new profile nothing was saved when I was reloading `chrome-extension://jjmflmamggggndanpgfnpelongoepncg/profiles.html`.

I opened the console and see that  error message `Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded`

![image](https://user-images.githubusercontent.com/5678673/51332956-bfd7be00-1a4a-11e9-891d-152c57bc6ad1.png)

**Note:** I have 102 extension at this moment.

A workaround would be to have a fallback or an option to use **[chrome.storage.local](https://developer.chrome.com/apps/storage)** so the limitation would not be there.

I understand that using **[chrome.storage.local](https://developer.chrome.com/apps/storage)** I would lost the sync feature but I don't mind personally so having an option to choose the between "unlimited" storage for heavy extension users like me or using the current storage for light/moderate users that want to be able to sync would be the better solution IMO.

Regards :octocat:

**Comment by mikhoul** [comment]
I've experimented and found that with my 102 extension I can save a maximum of only 2 profiles before hitting the quota limit.

**Comment by sergiokas** [comment]
Fixed in `v1.10.0`, if the number of extensions/profiles exceeds Google's quota, they'll be saved locally instead.
