### ISSUE TITLE
Extensions not being placed back in tolbar

### ISSUE THREAD

**Issue by regularlabs** [sergiokas/Extensity#46]
I like what Extensity does and that you can use profiles.
But I don't like my extensions being removed from the toolbar and not being placed back after they are switched back to active.

So can you fix this so Extensity remembers which extensions should be shown in the toolbar when active?

Or maybe even be able to control this separately in the profiles per extension?
That would allow you to have one profile to have an extension active and shown in the toolbar, and another active but hidden, and a third where it is inactive.

**Comment by gpion** [comment]
I totally agree, when switching back and forth between profiles, all extensions disabled in the source profile and enabled in the new one are initially hidden in chrome menu, not really practical

**Comment by MagTun** [comment]
This would be a great feature! The problem was already reported here but not yet addressed https://github.com/sergiokas/Extensity/issues/24

**Comment by regularlabs** [comment]
And seeing this is more than a year ago, chances are it will never be addressed.
The extension development seems dead in the water.
A shame.

**Comment by MagTun** [comment]
Possibly but in the readme, there were several update done in the last years, so not all hope are lost! I have seen that some computers don't have this problem, so maybe there is a tweak in Chrome settings to prevent this. I am still investigating it...

**Comment by MagTun** [comment]
Same problem on Chromium-based Edge.

**Comment by amitg87** [comment]
**Not possible as of right now**
There is no way we could override chrome behaviour of hiding extension in toolbar.
I don't see this getting addressed anytime soon.
There are no APIs available to manage the toolbar.
