### ISSUE TITLE
what does Chrome Cloud Storage sync mean?

### ISSUE THREAD

**Issue by Inilien** [sergiokas/Extensity#50]
Hi, I would like to ask to add more information into README about what exactly the Chrome Cloud Storage sync function does. It wasn't obvious for me what that means and I had to dig through old issues to find that information.  
For example, it would be nice to clarify these questions:
- What information is synchronized? My thinking was: since `Extensity` is an extension manager, probably it will synchronize settings of all extensions? E.g. I have installed extension foo and in its options I turned on option bar. Will that information be synchronized? Or only the list of installed extensions will be synced? Or only profiles (and list of installed extensions Chrome manages by itself)  
- How can I check if this feature is working correctly? Would be nice to see some green text in case if saving information to Chrome Cloud Storage was done successfully.

**Comment by karolzlot** [comment]
only the list of installed extensions will be synced

**Comment by spinozaNNN** [comment]
I'm getting "You have too many Extensions or Profiles to sync with Google. Your Profiles are still saved, but only for this browser" error in Extensity.  What are the limits of each?  

Thanks.

**Comment by sergiokas** [comment]
This: https://developer.chrome.com/docs/extensions/mv2/reference/storage

Chrome has been bumping up extensions supported storage in newer Chrome versions, so this message should be less frequent.

Note: I wouldn't request unlimited storage for Extensity. Anything that would potentially flag the extension as harmful is an anti-feature.
