### ISSUE TITLE
When scrolling extensions can't access off screen extensions

### ISSUE THREAD

**Issue by boardtc** [sergiokas/Extensity#51]
When I scroll to the bottom of the popup list, it immediately jumps back to the top of the list meaning any extension that I need to scroll to can't be accessed

![scroll jump](https://user-images.githubusercontent.com/214808/65765128-433fc800-e11f-11e9-8d9b-1b0d408f4e5b.png)

**Comment by sergiokas** [comment]
@boardtc that screenshot is definitely *not* from Extensity; may belong to some other similar tool I don't control.
