### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by ixanga** [sergiokas/Extensity#6]
I am really sorry that I have to go back to using Switcher because Extensity was better. Thank you for having made such a great extension. It did make things more efficient for me. But now instead of being able to turn one extension on and another off as I pleased, which I did frequently. I wiill now have to make dozens of profiles. One for when I am using this site and another for when I am using a different site and can't switch tabs because there is no way of turning on this particular search engine and ublock off and font changer on and all the rest. There wasn't even one request for anything similar to this in the Extensions store? Why would you fix something that wasn't broken? Because you are a developer and must develop or what?  Well, thanks again, it was one of the best extensions I had. Now it would complicate things too much.

**Comment by sergiokas** [comment]
@ixanga not really... you can just avoid the profiles feature entirely and use Extensity the way you were using it before.
