### ISSUE TITLE
[Feature Request] Pin Specified Extensions in Profiles

### ISSUE THREAD

**Issue by psxvoid** [sergiokas/Extensity#61]
Hi,

Currently, when switching between profiles some extensions may get "unpinned" from the extensions bar. It seems like Chrome not always correctly restores pinned/unpinned extensions states. It would be superb to have an additional option for each extension in Profiles to specify whether it should be pinned or not.

**Comment by adrianhalid** [comment]
Hi psxvoid,

I think I might have found a work around.

I have 3 profiles

Default
Development
Shopping

I would be always be fighting which items are pinned when I swapped between Development and Shopping.

The work around is to create another profile called "All".

Then select the All profile and pin everything.

Now when I switch between Default, Development and Shopping every item in the selected profile is pinned.

It might not be exactly what you wanted but it seems to work for me.

**Comment by sergiokas** [comment]
@adrianhalid workaround may work, however Chrome decides what to pin or unpin (apparently in a random manner) when extensions are disabled. Also there's no API support for pin/unpin yet. See https://twitter.com/ExtensityChrome/status/1301165128742834183
