### ISSUE TITLE
Feature Suggestion: Sticky Extensions

### ISSUE THREAD

**Issue by tomahawkzx** [sergiokas/Extensity#7]
It would be great if it were possible to stick to top (or even reorder) our preferred extensions within the list. 

![image](https://cloud.githubusercontent.com/assets/18285859/16117266/99c9c046-33a7-11e6-8e08-7c79956ca46d.png)
![image](https://cloud.githubusercontent.com/assets/18285859/16117566/2aa0049e-33a9-11e6-86e6-d57f48520948.png)

I took a look at the source code, but due to lack of knowledge on Extensions Development at the moment, I can't go any further to help.

**Comment by sammarcus** [comment]
@tomahawkzx now you can float your enabled extensions to the top! toggle is in prefs.

**Comment by sergiokas** [comment]
@tomahawkzx @sammarcus yep, check the settings, new option is there.

**Comment by sammarcus** [comment]
@sergiokas 😎 🙏
