### ISSUE TITLE
[Feature Request] Option to to only effect specific extensions and leave others unchange

### ISSUE THREAD

**Issue by Mark-Joy** [sergiokas/Extensity#73]
Thank you for the Great Extensity!

Say I have extensions A, B, C and profileAB.
If I turn on profileAB, then extensions A and B are turned on, but not changing/effect the state of extension C
If I turn off profileAB, then extensions A and B are turned off, but not changing/effct the sate of extension C
Is it possible?

**Comment by rrrix** [comment]
@Mark-Joy - this is what the `Keep Always On extensions enabled when switching everything off` option does (the very last option on the Extensity Options screen).

![image](https://user-images.githubusercontent.com/3194704/201436107-3a7992bf-8224-4aaf-a308-3d185503dbfa.png)

**Comment by Mark-Joy** [comment]
@rrrix
Thank you very much!
After a long while of using this extension, I think what I meant was: Feature Suggestion: Multiple active profiles #8
