### ISSUE TITLE
[Feature Request] Pin and Unpin Extensions Easily With Extensity

### ISSUE THREAD

**Issue by TheIanKirby** [sergiokas/Extensity#74]
It would be cool if the extensions could be pinned and unpinned just as easily as it is to enable and disable them.
It would also be cool if Extensity could automatically pin a newly installed extension as an option.

(Which enabled extensions to pin and unpin could be saved on the profiles, including "Always On".
Give the option to auto-pin a newly enabled extension.
Any pinned disabled extension shouldn't display on the browser's extension bar by default but should display once it's newly enabled.)

**Comment by Danie10** [comment]
Yes this would truly be useful

**Comment by sergiokas** [comment]
As far as I can tell the Chrome extensions management API dosn't have a method to do it (only to read the state of it).

Closing, would reopen if Google implements support for it.
