### ISSUE TITLE
Feature Suggestion: Multiple active profiles

### ISSUE THREAD

**Issue by willprice** [sergiokas/Extensity#8]
Hi,

First off, thanks for your excellent extension, it's very useful!

I've a feature suggestion to make the profiles feature even better. Here's the use case: I have multiple profiles for work and home, one for linux and one for windows, ideally I'd be able to enable multiple profiles at the same time so that I can have 'work' and 'linux' active.

Cheers

**Comment by amitg87** [comment]
This feature is already supported. You can create profiles and selectively enable/disable plugins based on profile.

**Comment by sergiokas** [comment]
@cecoates This will be partially supported with the addition of "Always On" profiles (a special list of extensions that will always be enabled and don't need to be included on every specific list).

While it just mitigates the problem and doesn't really addresses the exact issue you're describing, I'm usually not inclined to include too many "advanced" features that may result in confusion for the average user.

**Comment by Mark-Joy** [comment]
Would love to see this feature supported, please!
