### ISSUE TITLE
Java issues/extension deprecated?

### ISSUE THREAD

**Issue by YesTrustMe** [sergiokas/Extensity#86]
Extension hasn't been updated since November 2021. Is developer still supporting it?

Also, does this extension use java in any way? It seems I am having browser issues with java when I am using this extension. I am not 100% certain as I am still troubleshooting. However, since uninstalling it I haven't had any issues.

**Comment by sergiokas** [comment]
Updated extension to support Manifest v3, will continue to work with newer Chrome versions.

No Java whatsoever.
